### ISSUE TITLE
CDK Substructure Search: null pointer exception with flow variable

### ISSUE THREAD

**Issue by Jeany-P** [cdk/nodes4knime#11]
CDK Substructure Search node: when a flow variable is used one cannot open the configuration dialogue again because of a null pointer exception (see attached KNIME workflow
[CDK_Substructure_bug.knwf.zip](https://github.com/cdk/nodes4knime/files/3289596/CDK_Substructure_bug.knwf.zip)
).

**Comment by webbres** [comment]
The flow variables isn't the issue, but when setting a flow variable a user doesn't need to draw the substructure and thus the error is triggered. 

PR raised with a fix
