### ISSUE TITLE
Plugin not compatible with KNIME 4.0

### ISSUE THREAD

**Issue by webbres** [cdk/nodes4knime#8]
The plugin specifies the max version is 4.0 and needs to be changed to 5.0. 

I can submit a pull request for this if you'd like?

**Comment by webbres** [comment]
I'm not sure how to link a pull request in github with an issue. 

This PR should fix this issue and allow KNIME to build for 4.0: https://github.com/cdk/nodes4knime/pull/9

Should another release branch be made for 4.0? It seems KNIME 3.5, 3.6 and 3.7 are all using the 3.5 branch?

**Comment by egonw** [comment]
Creating a 4.0 branch makes sense to me.

**Comment by webbres** [comment]
Thank you for merging the PR 👍 

I can update the KNIME 4 jenkins build if you could make the branch? The build currently works but it doesn't look like it can actually be installed into the KNIME 4 application.

**Comment by egonw** [comment]
https://github.com/cdk/nodes4knime/tree/dev/knime4

**Comment by webbres** [comment]
The trunk build can now be installed and I've updated the version 4 build to use the new branch. Just waiting for the built files to propagate into the update site.

Provisionally all looks fine for version 4 now.
